export const variable = "#ffffff"
export const active_3 = "#D81212"
export const active_2 = "#EB4646"
export const active_1 = "#ffa8a8"
export const special_3 = "#cf24fa"
export const special_2 = "#fb4cfb"
export const special_1 = "#f9a8f9"
export const special_x1 = "#6F5BC7"
export const regexp = "#4fbd8b"
export const property_1 = "#D2FAB7"
export const property_builtin = "#89E04F"
export const property_magic = "#FDACF6"
export const property_typish = "#B5EDFF"
export const keyword_1 = "#8F79F1"
export const keyword_2 = "#9E85F8"
export const keyword_3 = "#5B9FFD"
export const keyword_4 = "#4D5EF5"
export const op_css = "#91F78F"
export const string_1 = "#5FD9D9"
export const string_2 = "#0ABCCC"
export const string_3 = "#0A7BCC"
export const string_special_token = "#FF7B72"

export const type_arg = "#FA9542"
export const namespace = "#00D977"
export const strong_object = "#01FF78"
export const medium_object = "#8488FF"
export const weak_object = "#69DCFF"
export const alt_object = "#EEFF00"
export const special_object = "#cf24fa"
export const active_magic = "#fb4cfb"
export const light_text = "#C5C5C5"
export const super_light_text = "#6E6E6E"
export const main_active = "#ee4747"
export const active_alt = "#D3FA69"
export const color_value = "#74C5F7"

export const hard_unit_1 = "#f838e4"
export const hard_unit_2 = "#8FFA24"
export const flex_unit_1 = "#f838e4"
export const flex_unit_2 = "#00ffae"
export const magic_unit_1 = "#FBFF00"
export const magic_unit_2 = "#FBFF00"

export const interjection = "#FF0000"

export const self = special_1

export const package_name = "#804A7A"
export const imported = "#9DFF00"
export const moduleReference = "#79C0FF"
export const comment = "#536E5E"
export const comment_meta_type = "#729C68"
export const comment_meta_var = "#B4E3A9"
export const comment_ref = "#A5D6FF"
export const punctuation = "#8B8B8B"
