import diff from "./ide/diff.js"
import editor from "./ide/editor.js"
import jsdoc from "./langs/jsdoc.js"
import csharp from "./langs/csharp.js"
import fsharp from "./langs/fsharp.js"
import css from "./langs/css.js"
import js from "./langs/js.js"
import githubActions from "./langs/github-actions.js"
import tex from "./langs/tex.js"
import markdown from "./langs/markdown.js"
import json from "./langs/json.js"
import yaml from "./langs/yaml.js"
import toml from "./langs/toml.js"
import shell from "./langs/shell.js"
import python from "./langs/python.js"

import core from "./parts/core.js"
import modules from "./parts/modules.js"
import types from "./parts/types.js"
import regexp from "./parts/regexp.js"
import strings from "./parts/strings.js"
import vriables from "./parts/variables.js"


